# Generated by Django 5.1.6 on 2025-02-09 11:45

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_job_title', models.CharField(max_length=255, null=True)),
                ('goal_job_title', models.CharField(max_length=255, null=True)),
                ('education', models.CharField(max_length=255, null=True)),
                ('education_field', models.CharField(max_length=255, null=True)),
                ('graduation_year', models.DateField(null=True)),
                ('technical_skills', models.TextField(blank=True, null=True)),
                ('soft_skills', models.TextField(blank=True, null=True)),
                ('experience_job_title', models.CharField(max_length=255, null=True)),
                ('experience_duration', models.IntegerField(null=True)),
                ('year_of_resignation', models.DateField(blank=True, null=True)),
                ('city1', models.CharField(blank=True, max_length=100, null=True)),
                ('city2', models.CharField(blank=True, max_length=100, null=True)),
                ('city3', models.CharField(blank=True, max_length=100, null=True)),
                ('availability', models.CharField(blank=True, choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=10, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=api.models.CareerGoal.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='GeminiResonse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(default='null', max_length=100)),
                ('response', models.CharField(max_length=755)),
                ('user', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
    ]
