# Generated by Django 5.1.6 on 2025-02-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminiresponse',
            name='response',
            field=models.TextField(),
        ),
    ]
