# Generated by Django 5.1.6 on 2025-02-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_careergoal_current_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careergoal',
            name='current_job_title',
            field=models.CharField(blank=True, default='null', max_length=255, null=True),
        ),
    ]
