# Generated by Django 5.1.6 on 2025-02-09 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_geminiresonse_field_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminiresonse',
            name='field',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='geminiresonse',
            name='response',
            field=models.CharField(max_length=755),
        ),
        migrations.AlterField(
            model_name='geminiresonse',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
