# Generated by Django 5.1.6 on 2025-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_geminiresonse_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careergoal',
            name='current_job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
